### ISSUE TITLE
getPath() - with holes

### ISSUE THREAD

**Issue by oliverdolgener** [seanofw/graphics-region#1]
First of all thank you so much for this excellent library. I use it with great joy. It makes things so much easier for me.

As for my question: How do you deal with holes in a region when extracting corner points with `getPath()`?

In my use case I need to union multiple rectangles dynamically which works just fine until I create a region with one or more holes inside.

I hope I could explain my problem well enough.

Thanks in advance!

**Comment by seanofw** [comment]
`getPath()` should return an array of arrays of points, per its documentation:

```
	/**
	 * Calculate a minimal set of nonoverlapping nonadjoining clockwise polygons that describe this region.
	 * The result will be an array of arrays of points, like this:
	 *     [
	 *         [{x:1, y:2}, {x:3, y:2}, {x:3, y:6}, {x:1, y:6}],    // Polygon 1
	 *         [{x:7, y:5}, {x:8, y:5}, {x:8, y:8}, {x:10, y:8}, {x:10, y:9}, {x:7, y:9}]    // Polygon 2
	 *     ]
	 */
```

So you should see a a first set of points for the outer "containing" polygon, and a second set of points representing the "hole".

**Comment by seanofw** [comment]
For what it's worth, you can see this working on the [Live Demo](https://seanofw.github.io/region2d/#LiveDemo) page; overlap some rectangles, set them all to `Union` mode, and notice how `getPath()` correctly computes the "hole" inside by generating multiple polygons (drawn as the dashed lines):

![image](https://user-images.githubusercontent.com/981716/47873030-85189f00-dde6-11e8-9fbf-001d4d962643.png)

**Comment by oliverdolgener** [comment]
Thanks for the quick response. That's pretty neat but how do I know if polygon from the array is actually a hole or another 'real' polygon?

**Comment by seanofw** [comment]
"Solid" polygons have overall clockwise windings, while "holes" have overall counterclockwise windings.  There exist algorithms for determining whether a polygon is clockwise or counterclockwise (see [StackOverflow](https://stackoverflow.com/questions/1165647/how-to-determine-if-a-list-of-polygon-points-are-in-clockwise-order) for more details).

**Comment by oliverdolgener** [comment]
Oh that makes sense. Thanks for the hint!
